syntax on
"filetype on
"filetype plugin on
"filetype indent on

"if has("autocmd")
"    autocmd FileType python colorscheme evening
"    autocmd FileType python set background=dark
"
"    autocmd FileType html colorscheme slate
"    autocmd FileType html set background=dark
"    autocmd FileType css colorscheme morning
"    autocmd FileType css set background=dark
"    autocmd FileType javascript colorscheme desert
"    autocmd FileType javascript set background=dark
"    autocmd FileType typescript colorscheme desert
"    autocmd FileType typescript set background=dark
"
"    autocmd FileType java colorscheme blue
"    autocmd FileType java set background=dark
"    autocmd FileType kotlin colorscheme desert
"    autocmd FileType kotlin set background=dark
"
"    autocmd FileType json colorscheme ron
"    autocmd FileType json set background=dark
"    autocmd FileType yaml colorscheme ron
"    autocmd FileType yaml set background=dark
"
"    autocmd FileType * set number
"    autocmd FileType * set hlsearch
"    autocmd FileType * set showmatch
"endif

set background=dark
set showcmd
set ruler
set cursorline
set number
set tabstop=4
set hlsearch


